MyEvents/MyEvents.Web/Areas/Organizer/Controllers/ScheduleController.cs
using System;
using System.Web.Mvc;
using MyEvents.Data;
using MyEvents.Web.Mappers;
using MyEvents.Web.Authentication;
using System.Web;
using MyEvents.Model;
using MyEvents.Web.Services;

namespace MyEvents.Web.Areas.Organizer.Controllers
{
    /// <summary>
    /// The schedule controller.
    /// </summary>
    [MyEvents.Web.Authentication.Authorize]
    public class ScheduleController : Controller
    {
        private readonly ISessionRepository _sessionRepository;
        private readonly IEventDefinitionRepository _eventDefinitionRepository;
        private readonly IAuthorizationService _authorizationService;

        /// <summary>
        /// Schedule controller constructor.
        /// </summary>
        public ScheduleController(ISessionRepository sessionRepository, IEventDefinitionRepository eventDefinitionRepository, IAuthorizationService authorizationService)
        {
            _sessionRepository = sessionRepository;
            _eventDefinitionRepository = eventDefinitionRepository;
            _authorizationService = authorizationService;
        }

        /// <summary>
        /// Index action.
        /// </summary>
        /// <param name="eventDefinitionId"></param>
        /// <returns></returns>
        public ActionResult Index(int eventDefinitionId)
        {
            return View(eventDefinitionId);
        }

        /// <summary>
        /// Gets the shedule information as json.
        /// </summary>
        /// <param name="identity"></param>
        /// <param name="eventDefinitionId"></param>
        /// <returns></returns>
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult GetSheduleInfo(MyEventsIdentity identity, int eventDefinitionId)
        {
            var eventDefinition = _eventDefinitionRepository.GetById(eventDefinitionId);
            
            _authorizationService.ValidateEventAuthorization(identity, eventDefinition);

            var mapper = new EventDefinitionToScheduleViewModelMapper();
            var viewModel = mapper.Map(eventDefinition);

            return Json(viewModel, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Updates the session.
        /// </summary>
        /// <param name="identity"></param>
        /// <param name="sessionId"></param>
        /// <param name="startTime"></param>
        /// <param name="duration"></param>
        /// <param name="roomNumber"></param>
        [HttpPost]
        public void UpdateSession(MyEventsIdentity identity, int sessionId, DateTime startTime, int duration, int roomNumber)
        {
            var session = _sessionRepository.Get(sessionId);

            _authorizationService.ValidateSessionAuthorization(identity, session);

            session.StartTime = startTime;
            session.Duration = duration;
            session.RoomNumber = roomNumber;

            _sessionRepository.Update(session);
        }
    }
}

MyEvents/MyEvents.Web/Areas/Organizer/Controllers/SessionController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyEvents.Data;
using MyEvents.Model;
using MyEvents.Web.Areas.Organizer.Models;
using MyEvents.Web.Authentication;
using System;
using MyEvents.Web.Services;

namespace MyEvents.Web.Areas.Organizer.Controllers
{
    /// <summary>
    /// Session controller.
    /// </summary>
    [MyEvents.Web.Authentication.Authorize]
    public class SessionController : Controller
    {
        private readonly ISessionRepository _sessionRepository;
        private readonly IMaterialRepository _materialRepository;
        private readonly IEventDefinitionRepository _eventsRepository;
        private readonly IAuthorizationService _authorizationService;

        /// <summary>
        /// Session controller constructor.
        /// </summary>
        /// <param name="sessionRepository">The session repository.</param>
        /// <param name="materialRepository">The material repository.</param>
        /// <param name="eventsRepository">The events repository.</param>
        /// <param name="authorizationService">The authorization service.</param>
        public SessionController(ISessionRepository sessionRepository, IMaterialRepository materialRepository, IEventDefinitionRepository eventsRepository, IAuthorizationService authorizationService)
        {
            _sessionRepository = sessionRepository;
            _materialRepository = materialRepository;
            _eventsRepository = eventsRepository;
            _authorizationService = authorizationService;
        }

        /// <summary>
        /// Manage action.
        /// </summary>
        /// <param name="identity"></param>
        /// <param name="eventDefinitionId"></param>
        /// <returns></returns>
        public ActionResult Manage(MyEventsIdentity identity, int eventDefinitionId)
        {
            var sessions = _sessionRepository.GetAll(eventDefinitionId);
            var viewModel = new ManageSessionViewModel()
                                {
                                    EventDefinitonId = eventDefinitionId,
                                    Sessions = sessions
                                };

            return View(viewModel);
        }

        /// <summary>
        /// Create action.
        /// </summary>
        /// <param name="eventDefinitionId"></param>
        /// <returns></returns>
        public ActionResult Create(int eventDefinitionId)
        {
            var session = new Session { EventDefinitionId = eventDefinitionId };
            return View("Form", session);
        }

        /// <summary>
        /// Edit action.
        /// </summary>
        /// <param name="identity"></param>
        /// <param name="sessionId"></param>
        /// <returns></returns>
        public ActionResult Edit(MyEventsIdentity identity, int sessionId)
        {
            var session = _sessionRepository.Get(sessionId);

            _authorizationService.ValidateSessionAuthorization(identity, session);

            return View("Form", session);
        }

        /// <summary>
        /// Save action.
        /// </summary>
        /// <param name="identity"></param>
        /// <param name="session"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(MyEventsIdentity identity, Session session)
        {
            if (!ModelState.IsValid)
                return PartialView("Form", session);

            _authorizationService.ValidateSessionAuthorization(identity, session);
            SaveSession(session);

            return RedirectToAction("Manage", new { eventDefinitionId = session.EventDefinitionId });
        }

        /// <summary>
        /// Deletes the session.
        /// </summary>
        /// <param name="identity"></param>
        /// <param name="sessionId"></param>
        /// <param name="eventDefinitionId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(MyEventsIdentity identity, int sessionId, int eventDefinitionId)
        {
            _authorizationService.ValidateSessionAuthorization(identity, sessionId);
            _sessionRepository.Delete(sessionId);

            return RedirectToAction("Manage", new { eventDefinitionId = eventDefinitionId });
        }

        /// <summary>
        /// Upload material action.
        /// </summary>
        /// <param name="identity"></param>
        /// <param name="sessionId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UploadMaterial(MyEventsIdentity identity, int sessionId)
        {
            if (Request.Files != null && Request.Files.Count > 0)
            {
                HttpPostedFileBase file = Request.Files[0];
                var fileBytes = new byte[file.ContentLength];
                file.InputStream.Read(fileBytes, 0, (int)file.ContentLength);

                if (fileBytes.Length != 0)
                {
                    _authorizationService.ValidateSessionAuthorization(identity, sessionId);

                    var material = new Material
                    {
                        SessionId = sessionId,
                        Name = HttpUtility.HtmlDecode(file.FileName),
                        ContentType = file.ContentType,
                        Content = fileBytes
                    };
                    _materialRepository.Add(material);
                    return PartialView("MaterialRow", material);
                }
            }
            return null;
        }

        /// <summary>
        /// Delete the material action.
        /// </summary>
        /// <param name="identity"></param>
        /// <param name="materialId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteMaterial(MyEventsIdentity identity, int materialId)
        {
            var material = _materialRepository.Get(materialId);
            int sessionId = material.SessionId;

            _authorizationService.ValidateSessionAuthorization(identity, sessionId);
            _materialRepository.Delete(materialId);

            return RedirectToAction("Materials", new { sessionId = sessionId });
        }

        /// <summary>
        /// Manage action.
        /// </summary>
        /// <param name="sessionId"></param>
        /// <returns></returns>
        public ActionResult Materials(int sessionId)
        {
            var materials = _materialRepository.GetAll(sessionId).ToList();
            var viewModel = new ManageMaterialsViewModel()
            {
                SessionId = sessionId,
                Materials = materials
            };

            return View(viewModel);
        }

        /// <summary>
        /// Action to get the material file.
        /// </summary>
        /// <param name="materialId"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetMaterial(int materialId)
        {
            var material = _materialRepository.Get(materialId);
            return File(material.Content, material.ContentType, material.Name);
        }

        private void SaveSession(Session session)
        {
            bool isUpdate = session.SessionId > 0;

            if (isUpdate)
            {
                var sessionToUpdate = _sessionRepository.Get(session.SessionId);
                MapSession(sessionToUpdate, session);
                _sessionRepository.Update(sessionToUpdate);
            }
            else
            {
                _sessionRepository.Add(session);
            }
        }

        private void MapSession(Session sessionToUpdate, Session session)
        {
            sessionToUpdate.Biography = session.Biography;
            sessionToUpdate.Description = session.Description;
            sessionToUpdate.RoomNumber = session.RoomNumber;
            sessionToUpdate.Speaker = session.Speaker;
            sessionToUpdate.Title = session.Title;
            sessionToUpdate.TwitterAccount = session.TwitterAccount;
        }
    }
}

MyEvents/MyEvents.Web/Areas/Organizer/Views/Session/Form.cshtml
@model MyEvents.Model.Session
@{
    ViewBag.Title = "my events - session";
}
<div id="session-form" class="form">
    <span class="section-title">@(Model.SessionId == 0 ? "create new " : "edit ")
        session</span>
    @using (Html.BeginForm("Save", "Session", "Post"))
    {
        <section class="box opacity-background">
            @Html.HiddenFor(model => model.SessionId)
            @Html.HiddenFor(model => model.EventDefinitionId)
            <div class="wrapper">
                <div class="left half">
                    <div class="field">
                        <label for="Title">title</label>
                        @Html.EditorFor(model => model.Title)
                    </div>
                    <div class="field">
                        <label for="Description">description</label>
                        @Html.TextAreaFor(model => model.Description, new { rows = "10", @class = "text-box" })
                    </div>
                </div>
                <div class="right half">
                    <div class="field">
                        @Html.LabelFor(model => model.Speaker)
                        @Html.EditorFor(model => model.Speaker)
                    </div>
                    <div class="field">
                        @Html.LabelFor(model => model.Biography)
                        @Html.TextAreaFor(model => model.Biography, new { rows = "10", @class = "text-box" })
                    </div>
                    <div class="field">
                        @Html.LabelFor(model => model.TwitterAccount)
                        @Html.EditorFor(model => model.TwitterAccount)
                    </div>
                </div>
            </div>
            <section id="buttons" class="right">
                @Html.ActionLink("cancel", "Manage", new { eventDefinitionId = Model.EventDefinitionId }, new { @class = "button" })
                <input id="save-session-button" type="submit" value="save" class="button button-highlighted" />
            </section>
        </section>
    }
</div>

MyEvents/MyEvents.Web/Areas/Organizer/Views/Session/Manage.cshtml
@model MyEvents.Web.Areas.Organizer.Models.ManageSessionViewModel
@{
    ViewBag.Title = "my events - sessions";
}
@section Actions
{
    <section class="actions right menu">
        @Html.ActionLink("create new session", "Create", "Session", new { eventDefinitionId = Model.EventDefinitonId }, new { @class = "button button-highlighted" })
        @Html.ActionLink("manage schedule", "Index", "Schedule", new { eventDefinitionId = Model.EventDefinitonId }, new { @class = "button" })
    </section>
}

<section id="all-sessions">
    <span class="section-title">all sessions</span>
    <section class="list">
        <section class="headers">
            <span class="field extra-big uppercase">Session</span>
            <span class="field small uppercase center">Edit</span>
            <span class="field uppercase center">Materials</span>
            <span class="field small uppercase center">Delete</span>
        </section>

        @foreach (var session in Model.Sessions)
        {
            <article class="detail">
                <span class="field extra-big" title="@session.Title">@session.Title</span>
                <span class="field small center">
                    <a href="@Url.Action("Edit", "Session", new { sessionId = session.SessionId })" title="edit session">
                        <img src="@Url.Content("~/Styles/Images/pencil.png")" />
                    </a>
                </span>
                <span class="field center">
                    <a href="@Url.Action("Materials", "Session", new { sessionId = session.SessionId })" title="manage materials">
                        <img src="@Url.Content("~/Styles/Images/materials.png")" />
                    </a>
                </span>
                <form class="field small center" action="@Url.Action("Delete", "Session", new { eventDefinitionId = session.EventDefinitionId, sessionId = session.SessionId })" method="post">
                <button type="button" value="delete" class="image-button" title="delete event" data-confirm="true" data-confirm-text="are you sure you want to delete this session?">
                    <img src="@Url.Content("~/Styles/Images/delete.png")" />
                </button>
                </form>
            </article>
        }
        @if (!Model.Sessions.Any())
        {
            <article class="detail no-data">
                there are no available sessions at this moment.
                <a href="@Url.Action("Create", "Session", new { eventDefinitionId = Model.EventDefinitonId })"> Do you want to create one?</a>
            </article>
        }
    </section>
</section>

MyEvents/MyEvents.Web/Areas/Organizer/Views/Session/MaterialRow.cshtml
@model MyEvents.Model.Material

<article class="detail">
    <a href="@Url.Action("GetMaterial", "Session", new { materialId = Model.MaterialId })" target="_blanck">
        <span class="field extra-big" title="@Model.Name">@Model.Name</span>
    </a>
    <form class="field small text-right" action="@Url.Action("DeleteMaterial", "Session", new { materialId = Model.MaterialId })" method="post">
        <button type="button" value="delete" class="image-button" title="delete material" data-confirm="true" data-confirm-text="are you sure you want to delete this material?">
            <img src="@Url.Content("~/Styles/Images/delete.png")" />
        </button>
    </form>

</article>

MyEvents/MyEvents.Web/Areas/Organizer/Views/Session/Materials.cshtml
@using System.Web.Optimization
@model MyEvents.Web.Areas.Organizer.Models.ManageMaterialsViewModel
@{
    ViewBag.Title = "my events - materials";
}

<span class="section-title">materials</span>

<span>upload materials</span>
<section id="upload">
    <input id="sessionId" type="hidden" value="@Model.SessionId"/>
    <div class="file-picker">
        <input id="materialFileUploader" name="materialFileUploader" type="file" />
        <img id="icon" src="@Url.Content("~/Styles/Images/materials.png")" />
    </div>
</section>
<section id="materialList" class="list">
    @foreach (var material in Model.Materials)
    {
        Html.RenderPartial("MaterialRow", material);
    }
</section>

@section scripts
{
    @Scripts.Render("~/Organizer/Session/ManageMaterialsScripts/")
}